site_name: Data Journey
site_url: https://irchanbani.com
theme:
  name: material

repo_name: irchanbani/irchanbani.github.io
repo_url: https://github.com/irchanbani/irchanbani.github.io

plugins:
  - search
  - blog